export { default as Login } from './Login';
export { default as Overview } from './overview';
export { default as People } from './people';
export { default as Species } from './species';
export { default as Starships } from './starships';
export { default as Film } from './Film';
export { default as Person } from './Person';
export { default as Starship } from './Starship';
export { default as Specie } from './Specie';
