export { default as Login } from './Login';
export { default as Overview } from './Overview';
export { default as People } from './People';
export { default as Species } from './Species';
export { default as Starships } from './Starships';
export { default as Film } from './Film';
export { default as Person } from './Person';
export { default as Starship } from './Starship';
export { default as Specie } from './Specie';